### ISSUE TITLE
Syscall support: pread and pwrite

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/krf#4]
Docs: `man 2` and https://filippo.io/linux-syscall-table/

These belong in the `fs` and `io` groups, like `read` and `write`.

**Comment by woodruffw** [comment]
The full list:

- [ ] `pread`
- [ ] `pwrite`
- [ ] `readv`
- [ ] `writev`
- [ ] `preadv`
- [ ] `pwritev`

It looks like glibc exposes a few different wrappers for these, but the general error lists should be correct.

**Comment by layderv** [comment]
Should this be closed?

**Comment by woodruffw** [comment]
Yep, closing.
