### ISSUE TITLE
Make install rule

### ISSUE THREAD

**Issue by hmwildermuth** [trailofbits/krf#52]
Would install `krfexec` and `krfctl` in `/usr/bin` (or whatever prefix).

Should it also internally call the `insmod` rule?

**Comment by woodruffw** [comment]
> Would install `krfexec` and `krfctl` in `/usr/bin` (or whatever prefix).

👍 



> Should it also internally call the `insmod` rule?

I'd say no; what it could do is install the module to the standard location (`/lib/modules` I think?).

**Comment by hmwildermuth** [comment]
> I'd say no; what it could do is install the module to the standard location (/lib/modules I think?).

It seems the purpose of keeping a module in `/lib/modules` is if we want to use `modprobe` to load it, which we don't (we currently use `insmod` and `rmmod`). So I'm not sure if it is necessary to install the module to a new location.

**Comment by woodruffw** [comment]
> It seems the purpose of keeping a module in `/lib/modules` is if we want to use `modprobe` to load it, which we don't (we currently use `insmod` and `rmmod`). So I'm not sure if it is necessary to install the module to a new location.

We'd probably change from `insmod` and `rmmod` to `modprobe` and `modprobe -r` as part of this changeset; more users are familiar with `modprobe` than the others anyways, and they're a bit "smarter" when errors occur.
