### ISSUE TITLE
Missing syscall might abort krfctl -P

### ISSUE THREAD

**Issue by disconnect3d** [trailofbits/krf#68]
When there is a missing syscall, a given `krfctl -P <profile>` might `abort`:
```
root@ubuntu-bionic:/home/vagrant/krf# krfctl -P fs
krfctl: couldn't find syscall: sysctl
```

From @woodruffw :
> I guess `fault_syscall` could return a `bool` and we could push the error behavior one layer up

Related code: https://github.com/trailofbits/krf/blob/master/src/krfctl/linux/linux.c#L46

**Comment by layderv** [comment]
Can I work on this?

The idea would be to keep the error message, but return error:bool up and disable the missing syscall? What's the behavior for error=true?

**Comment by woodruffw** [comment]
> The idea would be to keep the error message, but return error:bool up and disable the missing syscall? What's the behavior for error=true?

Yep, exactly. On `error=true` we'd presumably continue attempting to fault the other syscalls specified in the profile.

We should also prefix the message with `Warning: ` or similar to make it clear that the command hasn't failed outright.

**Comment by woodruffw** [comment]
(And yes, please feel free to work on it!)
