### ISSUE TITLE
krfctl describe profiles

### ISSUE THREAD

**Issue by disconnect3d** [trailofbits/krf#72]
Krfctl should be able to:
- list available profiles that can be passed to `krfctl -P <profile>`.
- describe profiles, i.e., tell that `mm` stands for memory management syscalls and what syscalls are included.
- maybe also have a descriptive describe profile mode where also the possible faults are listed? Though I am not sure if this is that useful as this can be grabbed directly from syscalls yaml files.

**Comment by disconnect3d** [comment]
The first item is solved by #74.

**Comment by woodruffw** [comment]
I'll spend a bit of time today doing the second.
